version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  pgbouncer:
    container_name: pgbouncer
    image: edoburu/pgbouncer:latest
    environment:
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=12345
      - DB_HOST=postgres
      - DB_NAME=postgres
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres
    ports:
      - "5432:5432"
    depends_on:
      - postgres

volumes:
  pgdata:
